name: the_gridlock
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #url_launcher: ^6.2.6
  font_awesome_flutter: ^10.9.1
  flutter_animate: ^4.5.1
  url_launcher: ^6.3.2
  google_fonts: ^6.3.1
  
flutter_launcher_icons: 
  
  android: true
  ios: true
  image_path: "asset/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/

  # fonts:
  #   - family: Game
  #     fonts:
  #       - asset: lib/assets/Lobster-Regular.ttf
  #   - family: Honk
  #     fonts:
  #       - asset: lib/assets/Honk.ttf
